### ISSUE TITLE
muparserx is not pinned / linked correctly

### ISSUE THREAD

**Issue by wshanks** [conda-forge/qiskit-aer-feedstock#3]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

In a new environment install, when trying to import from qiskit_aer, I get the following:

```
  File "/home/wshanks/.conda/envs/qiskit/lib/python3.11/site-packages/qiskit_aer/pulse/controllers/digest_pulse_qobj.py", line 25, in <module>                 
    from .pulse_utils import oplist_to_array                                                                                                                   
ImportError: libmuparserx.so.4.0.8: cannot open shared object file: No such file or directory
```

In my environment I had muparserx 4.0.11 installed. When I originally packaged qiskit-aer, I packaged muparserx 4.0.8 because that was what was in qiskit-aer's cmake configuration. Afterwards the bot opened a PR to bump the recipe to 4.0.11 which I merged. Now it appears that qiskit-aer is linking specifically to 4.0.8. So this problem did not become apparent until I updated the muparserx recipe.

@leofang Before I look into this further, do you know where the fix should go? I would guess either the run_exports for muparserx need to be tighter, the qiskit-aer muparserx dependency specification needs to be tighter, or the way qiskit-aer links to muparserx needs to be looser.

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by leofang** [comment]
Sorry @wshanks I was out. I can reproduce by simply `import qiskit_aer`. Checking.

**Comment by leofang** [comment]
#7 should fix it.
