### ISSUE TITLE
Support CUDA build

### ISSUE THREAD

**Issue by leofang** [conda-forge/qiskit-aer-feedstock#5]
We (NVIDIA) are helping CUDA 12 bring-up on conda-forge (https://github.com/conda-forge/staged-recipes/issues/21382) and I myself would not have extra energy for anything beyond that, but I'd like to get this done once I have spare time.

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
It seems https://github.com/Qiskit/qiskit-aer/issues/1686 is not yet fixed, and it'd be a blocker if we wanna enable a build that has all CPU/GPU backends. Such an all-in-one package would impact CPU-only users due to that issue. 

I can instead build two flavors (CPU-only, CPU+GPU), following [the UCX approach](https://github.com/conda-forge/ucx-split-feedstock/blob/main/recipe/meta.yaml). @wshanks thoughts? 🙂

**Comment by wshanks** [comment]
Sorry, I forgot to respond earlier. Is the UCX approach to have one meta.yaml with selectors that specify the CUDA dependencies when the CUDA tools are installed and then to specify different build images to control the CPU and CPU+GPU builds? That seems reasonable to me (but I am not an expert in building with CUDA with conda). The qiskit-aer CUDA build seems to be controlled by setting a single environment variable so it should not be hard to include in the single meta.yaml file.

You may already have seen that qiskit-aer is now changing the way to does its PyPI GPU builds [here](https://github.com/Qiskit/qiskit-aer/pull/1854). The next release (0.12.2) should be tagged soon ([here](https://github.com/Qiskit/qiskit-aer/pull/1864)).

**Comment by leofang** [comment]
> Is the UCX approach to have one meta.yaml with selectors that specify the CUDA dependencies when the CUDA tools are installed and then to specify different build images to control the CPU and CPU+GPU builds? That seems reasonable to me (but I am not an expert in building with CUDA with conda). 

This is more or less what'd happen, yes. I realized that we've made dramatic changes to UCX lately (we no longer separate CPU & GPU builds; it's all-in-one now). [This](https://github.com/conda-forge/ucx-split-feedstock/blob/65e8a970247c2e8179aa2ad62e6454e2541ea5df/recipe/meta.yaml) should have been the recipe to link to, sorry for confusing.

One thing to note is that the docker image is largely controlled in a global manner ([here](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/f8046bf6aea10929ffc2cbaa6a9d3572181adc0c/recipe/conda_build_config.yaml#L142-L151) and in the "[migrators](https://github.com/search?q=repo%3Aconda-forge%2Fconda-forge-pinning-feedstock+path%3Acuda*.yaml&type=code)"), so without specific reasons we usually don't overwrite the global setting. And yes, for CUDA 11 and earlier, the image to use would be different based on the CUDA version. For CUDA 12, we renovated the infrastructure lately (see [here](https://github.com/conda-forge/conda-forge.github.io/issues/1963)), so it'd again reuse most of the CPU infra, including the image.

> (but I am not an expert in building with CUDA with conda)

No worries, I'll get it set up and you can learn it along the way 🙂

> The qiskit-aer CUDA build seems to be controlled by setting a single environment variable so it should not be hard to include in the single meta.yaml file.

Yeah that's what I think too, but based on your update below I'd wait for 0.12.2.

> You may already have seen that qiskit-aer is now changing the way to does its PyPI GPU builds [here](https://github.com/Qiskit/qiskit-aer/pull/1854). The next release (0.12.2) should be tagged soon ([here](https://github.com/Qiskit/qiskit-aer/pull/1864)).

This is exciting, thanks for sharing Will! Glad to know the wheel demo that I did is helpful 🙂 Since the build system has changed, let's wait for a little. I am a bit occupied this week anyway.

**Comment by wshanks** [comment]
Closed by #19
